const express=require('express'),fs=require('fs'),fsp=fs.promises,path=require('path'),crypto=require('crypto'),{spawn}=require('child_process');
const PORT=Number(process.env.PORT||10000),ROOT=process.cwd(),PUBLIC=path.join(ROOT,'public'),DATA=path.join(ROOT,'data'),VIDEOS=path.join(DATA,'videos'),PROJECTS=path.join(DATA,'projects');
for(const d of [VIDEOS,PROJECTS])fs.mkdirSync(d,{recursive:true});
const app=express();app.use(express.json({limit:'4mb'}));app.use(express.static(PUBLIC));app.use('/media/videos',express.static(VIDEOS));app.use('/media/projects',express.static(PROJECTS));
const jobs=new Map();const safe=s=>String(s||'').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,80);
async function ff(){return(await import('ffmpeg-static')).default}
function run(bin,args){return new Promise((ok,no)=>{const p=spawn(bin,args,{stdio:['ignore','pipe','pipe']});let e='';p.stderr.on('data',d=>e+=d);p.on('error',no);p.on('close',c=>c?no(Error(e.slice(-12000)||'FFmpeg '+c)):ok(e))})}
async function gemini(prompt){const key=process.env.GEMINI_API_KEY;if(!key)throw Error('Falta GEMINI_API_KEY');const model=process.env.GEMINI_TEXT_MODEL||'gemini-3.6-flash';const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+model+':generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:prompt}]}]})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error?.message||'Gemini HTTP '+r.status);return d.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||''}
function json(s){const m=String(s).match(/\{[\s\S]*\}/);if(!m)throw Error('JSON de IA no válido');return JSON.parse(m[0])}
async function tts(text,out){if(!process.env.HF_TOKEN)throw Error('Falta HF_TOKEN');const{InferenceClient}=await import('@huggingface/inference'),client=new InferenceClient(process.env.HF_TOKEN),bin=await ff();const chunks=String(text).replace(/\s+/g,' ').match(/.{1,300}(?:\s+|$)/g)||[String(text)],dir=path.join(path.dirname(out),'tts');await fsp.mkdir(dir,{recursive:true});const files=[];for(let i=0;i<chunks.length;i++){const b=await client.textToSpeech({model:process.env.HF_TTS_MODEL||'facebook/mms-tts-spa',inputs:chunks[i].trim()}),f=path.join(dir,'part-'+String(i).padStart(4,'0')+'.wav');await fsp.writeFile(f,Buffer.from(await b.arrayBuffer()));files.push(f)}const list=path.join(dir,'list.txt');await fsp.writeFile(list,files.map(f=>"file '"+f.replace(/'/g,"'\\''")+"'").join('\n'));await run(bin,['-y','-f','concat','-safe','0','-i',list,'-c:a','pcm_s16le',out])}
async function mediaDuration(bin,f){const r=await run(bin,['-hide_banner','-i',f,'-f','null','-']);const m=String(r).match(/Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)/);return m?Number(m[1])*3600+Number(m[2])*60+Number(m[3]):60}
async function wiki(topic){try{const u='https://es.wikipedia.org/w/api.php?action=query&list=search&srsearch='+encodeURIComponent(topic)+'&srlimit=5&format=json&origin=*';const d=await(await fetch(u,{headers:{'User-Agent':'AutoTubeStudio/1.0'}})).json();return(d.query?.search||[]).map(x=>x.title+': '+String(x.snippet||'').replace(/<[^>]+>/g,' ')).join('\n')}catch{return ''}}
async function research(topic){const refs=await wiki(topic);return json(await gemini('Investiga editorialmente el tema "'+topic+'". Prepara un dossier para un guionista de YouTube. Usa conocimiento fiable y estas referencias de Wikipedia si ayudan:\n'+(refs||'(sin referencias)')+'\nIncluye resumen, hechos comprobables, contexto, ideas sorprendentes, advertencias sobre datos dudosos y fuentes. No inventes citas ni estadísticas. SOLO JSON: {"summary":"","facts":[""],"angles":[""],"cautions":[""],"sources":[""]}'))}
async function makeImage(prompt,i,dir){const p=prompt+', widescreen 16:9 YouTube documentary/educational frame, polished cinematic visual, consistent visual identity, detailed lighting and composition, no readable text, no logo, no watermark';const u='https://image.pollinations.ai/prompt/'+encodeURIComponent(p)+'?width=1280&height=720&nologo=true&seed='+(Date.now()+i*7919);const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(120000)});if(!r.ok)throw Error('Imagen HTTP '+r.status);const b=Buffer.from(await r.arrayBuffer());if(b.length<5000)throw Error('Imagen vacía');const f=path.join(dir,'scene-'+String(i).padStart(3,'0')+'.jpg');await fsp.writeFile(f,b);return f}
async function makeThumbnail(title,visual,dir){const p='YouTube thumbnail 16:9, cinematic, strong central subject, dramatic lighting, high contrast, clear visual hierarchy, intriguing but truthful, no readable text, no logo: '+title+'; '+visual;const u='https://image.pollinations.ai/prompt/'+encodeURIComponent(p)+'?width=1280&height=720&nologo=true&seed='+Date.now();const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(120000)});if(!r.ok)throw Error('Miniatura HTTP '+r.status);const b=Buffer.from(await r.arrayBuffer());const f=path.join(dir,'thumbnail.jpg');await fsp.writeFile(f,b);return f}
function stamp(x){const z=Math.floor(x),ms=Math.floor((x-z)*1000),h=Math.floor(z/3600),m=Math.floor(z%3600/60),s=z%60;return String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+','+String(ms).padStart(3,'0')}
async function srt(script,total,out){const a=String(script).match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[script],words=a.reduce((n,x)=>n+x.trim().split(/\s+/).length,0),rows=[];let t=0;a.forEach(x=>{const w=x.trim(),d=total*(w.split(/\s+/).length/words),b=Math.min(total,t+d);rows.push((rows.length+1)+'\n'+stamp(t)+' --> '+stamp(b)+'\n'+w+'\n');t=b});await fsp.writeFile(out,rows.join('\n'))}
async function generate(topic,minutes,j){const dir=path.join(PROJECTS,j.id);await fsp.mkdir(dir,{recursive:true});const mins=Math.max(5,Math.min(15,Number(minutes||process.env.AUTOMATION_MINUTES||7)));
j.stage='Investigación';j.progress=5;const dossier=await research(topic);await fsp.writeFile(path.join(dir,'01-investigacion.json'),JSON.stringify(dossier,null,2));
j.stage='Estructura';j.progress=15;const outline=json(await gemini('Diseña la estructura profesional de un vídeo de YouTube de '+mins+' minutos sobre "'+topic+'". Debe tener gancho, contexto, bloques de desarrollo, ejemplos, punto memorable y conclusión. Dossier:\n'+JSON.stringify(dossier)+'\nSOLO JSON: {"working_title":"","hook":"","sections":[{"heading":"","purpose":"","key_points":[""],"visual_direction":""}],"ending":""}'));await fsp.writeFile(path.join(dir,'02-estructura.json'),JSON.stringify(outline,null,2));
j.stage='Guion';j.progress=25;const plan=json(await gemini('Escribe el guion final en español para un vídeo de YouTube de '+mins+' minutos sobre "'+topic+'". Usa la investigación y estructura siguientes.\nINVESTIGACIÓN:\n'+JSON.stringify(dossier)+'\nESTRUCTURA:\n'+JSON.stringify(outline)+'\nLa narración debe ser natural, sin notas técnicas. Crea además un plan visual ligado a cada fragmento. Cada scene.narration debe ser consecutiva y cubrir todo el script. Aproximadamente '+Math.max(12,Math.round(mins*2.2))+' escenas. SOLO JSON: {"title":"","description":"","tags":[""],"script":"","scenes":[{"narration":"","image_prompt":"","purpose":""}]}'));await fsp.writeFile(path.join(dir,'03-guion.json'),JSON.stringify(plan,null,2));
j.stage='Narración';j.progress=35;const audio=path.join(dir,'voice.wav');await tts(plan.script,audio);const bin=await ff(),total=await mediaDuration(bin,audio);await srt(plan.script,total,path.join(dir,'subtitles.srt'));
j.stage='Recursos visuales';j.progress=45;const imgs=[];for(let i=0;i<plan.scenes.length;i++){j.stage='Recursos visuales '+(i+1)+'/'+plan.scenes.length;j.progress=45+Math.round(i/plan.scenes.length*35);try{imgs.push(await makeImage(plan.scenes[i].image_prompt,i,dir))}catch(e){j.warnings=(j.warnings||[]).concat(e.message)}}if(imgs.length<5)throw Error('No se generaron suficientes recursos visuales');
j.stage='Miniatura';j.progress=82;let thumb='';try{thumb=await makeThumbnail(plan.title,plan.scenes[0]?.image_prompt||topic,dir)}catch(e){j.warnings=(j.warnings||[]).concat(e.message)}
j.stage='Montaje';j.progress=87;const each=Math.max(2,total/imgs.length),list=path.join(dir,'timeline.txt');await fsp.writeFile(list,imgs.map(f=>"file '"+f.replace(/'/g,"'\\''")+"'\nduration "+each.toFixed(3)).join('\n')+'\nfile \''+imgs[imgs.length-1].replace(/'/g,"'\\''")+'\'');const visual=path.join(dir,'visual.mp4');await run(bin,['-y','-f','concat','-safe','0','-i',list,'-vf','scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080,format=yuv420p','-r','30','-c:v','libx264','-preset','veryfast','-crf','23','-movflags','+faststart',visual]);
const name='auto-'+Date.now()+'-'+safe(plan.title)+'.mp4',out=path.join(VIDEOS,name),sub=path.join(dir,'subtitles.srt').replace(/:/g,'\\:');await run(bin,['-y','-i',visual,'-i',audio,'-vf',"subtitles="+sub+":force_style='FontName=Arial,FontSize=20,PrimaryColour=&H00FFFFFF,OutlineColour=&H00000000,Outline=2,Shadow=1,Alignment=2,MarginV=35'",'-map','0:v','-map','1:a','-c:v','libx264','-preset','veryfast','-crf','23','-c:a','aac','-b:a','160k','-shortest','-movflags','+faststart',out]);
await fsp.writeFile(path.join(dir,'04-metadata.json'),JSON.stringify({title:plan.title,description:plan.description,tags:plan.tags,durationSeconds:Math.round(total),sceneCount:imgs.length,thumbnail:thumb?'/media/projects/'+j.id+'/thumbnail.jpg':null},null,2));
j.status='succeeded';j.progress=100;j.stage='Proyecto terminado';j.result={name:name,url:'/media/videos/'+encodeURIComponent(name),title:String(plan.title||topic).slice(0,100),description:String(plan.description||''),tags:Array.isArray(plan.tags)?plan.tags:[],durationSeconds:Math.round(total),sceneCount:imgs.length,thumbnail:thumb?'/media/projects/'+j.id+'/thumbnail.jpg':null,projectUrl:'/media/projects/'+j.id+'/'}}
function start(topic,minutes){const id='auto-'+Date.now();const j={id:id,status:'running',progress:0,stage:'Iniciando'};jobs.set(id,j);generate(topic,minutes,j).catch(e=>{j.status='failed';j.error=e.message;console.error('[AUTO]',e)});return j}
app.get('/health',(_,r)=>r.json({ok:true,service:'autotube-studio',gemini:!!process.env.GEMINI_API_KEY,tts:!!process.env.HF_TOKEN}));
app.post('/api/automation/generate',(q,r)=>{const topic=String(q.body?.topic||'').trim();if(!topic)return r.status(400).json({error:'Escribe un tema'});const j=start(topic,q.body?.minutes);r.status(202).json({jobId:j.id})});
app.get('/api/automation/status',(q,r)=>{const j=jobs.get(String(q.query.jobId||''));if(!j)return r.status(404).json({error:'No encontrado'});r.json(j)});
const tokenFile=path.join(DATA,'youtube-token.json'),secret=()=>String(process.env.YOUTUBE_CLIENT_SECRET||''),cfg=()=>({id:process.env.YOUTUBE_CLIENT_ID,secret:process.env.YOUTUBE_CLIENT_SECRET,redirect:process.env.YOUTUBE_REDIRECT_URI});
function state(){const raw=crypto.randomBytes(18).toString('hex');return raw+'.'+crypto.createHmac('sha256',secret()).update(raw).digest('hex')}
function valid(s){const p=String(s||'').split('.');if(p.length!==2)return false;const a=Buffer.from(p[1]),b=Buffer.from(crypto.createHmac('sha256',secret()).update(p[0]).digest('hex'));return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function saveToken(t){fs.writeFileSync(tokenFile,JSON.stringify(t,null,2),{mode:0o600})}function loadToken(){try{return JSON.parse(fs.readFileSync(tokenFile))}catch{return null}}
async function access(){let t=loadToken();if(!t&&process.env.YOUTUBE_REFRESH_TOKEN)t={refresh_token:process.env.YOUTUBE_REFRESH_TOKEN,created_at:0,expires_in:0};if(!t)return null;if(t.refresh_token&&Date.now()-t.created_at>(Number(t.expires_in||3600)-120)*1000){const c=cfg(),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.id,client_secret:c.secret,refresh_token:t.refresh_token,grant_type:'refresh_token'})}),d=await r.json();if(!r.ok)throw Error(d.error_description||d.error);t={...t,...d,refresh_token:t.refresh_token,created_at:Date.now()};saveToken(t)}return t.access_token}
app.get('/api/youtube/connect',(q,r)=>{const c=cfg();if(!c.id||!c.secret||!c.redirect)return r.status(500).send('Faltan credenciales de YouTube');const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.searchParams.set('client_id',c.id);u.searchParams.set('redirect_uri',c.redirect);u.searchParams.set('response_type','code');u.searchParams.set('scope','openid email profile https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtube.readonly');u.searchParams.set('access_type','offline');u.searchParams.set('prompt','consent');u.searchParams.set('state',state());r.redirect(u.toString())});
app.get('/api/youtube/callback',async(q,r)=>{try{if(!valid(q.query.state))throw Error('OAuth inválido');const c=cfg(),x=await(await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code:q.query.code,client_id:c.id,client_secret:c.secret,redirect_uri:c.redirect,grant_type:'authorization_code'})})).json();if(!x.access_token)throw Error(x.error_description||'Google rechazó la autorización');saveToken({...x,created_at:Date.now()});r.redirect('/?youtube=connected')}catch(e){r.status(500).send(e.message)}});
app.get('/api/youtube/status',async(_,r)=>{try{const a=await access();if(!a)return r.json({connected:false});const x=await(await fetch('https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true',{headers:{Authorization:'Bearer '+a}})).json(),c=x.items?.[0];r.json({connected:!!c,channel:c?{id:c.id,title:c.snippet?.title,thumbnail:c.snippet?.thumbnails?.default?.url}:null})}catch(e){r.json({connected:false,error:e.message})}});
async function upload(file,meta){const a=await access();if(!a)throw Error('YouTube no está conectado');const st=await fsp.stat(file),init=await fetch('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status',{method:'POST',headers:{Authorization:'Bearer '+a,'Content-Type':'application/json','X-Upload-Content-Length':String(st.size),'X-Upload-Content-Type':'video/mp4'},body:JSON.stringify({snippet:{title:String(meta.title||'Nuevo vídeo').slice(0,100),description:String(meta.description||''),tags:meta.tags||[],categoryId:'22'},status:{privacyStatus:meta.privacyStatus||'public',selfDeclaredMadeForKids:false}})}),loc=init.headers.get('location');if(!loc)throw Error('YouTube no inició la subida');const rr=await fetch(loc,{method:'PUT',headers:{Authorization:'Bearer '+a,'Content-Type':'video/mp4','Content-Length':String(st.size)},body:fs.createReadStream(file),duplex:'half'}),d=await rr.json().catch(()=>({}));if(!rr.ok)throw Error(d.error?.message||'Error subiendo a YouTube');return d}
app.post('/api/youtube/upload',async(q,r)=>{try{const f=path.join(VIDEOS,path.basename(q.body?.name||''));if(!fs.existsSync(f))throw Error('Vídeo no encontrado');r.json({ok:true,video:await upload(f,q.body)})}catch(e){r.status(500).json({error:e.message})}});
async function chooseTopic(){const niche=process.env.AUTOMATION_NICHE||'historias sorprendentes, curiosidades y explicaciones visuales';let recent='';try{const a=await access();if(a){const x=await(await fetch('https://www.googleapis.com/youtube/v3/search?part=snippet&forMine=true&type=video&order=date&maxResults=20',{headers:{Authorization:'Bearer '+a}})).json();recent=(x.items||[]).map(v=>v.snippet?.title||'').join(' | ')}}catch{}return json(await gemini('Elige un tema NUEVO para un vídeo de YouTube dentro de esta temática: '+niche+'. Debe ser evergreen, investigable, visual y diferente de estos títulos recientes del canal: '+recent+'. No repitas ni reformules esos temas. SOLO JSON: {"topic":"..."}')).topic}
app.post('/api/automation/daily',async(q,r)=>{try{if(!process.env.AUTOMATION_SECRET||q.get('x-automation-secret')!==process.env.AUTOMATION_SECRET)return r.status(401).json({error:'No autorizado'});const topic=await chooseTopic(),j=start(topic,process.env.AUTOMATION_MINUTES||7);while(j.status==='running')await new Promise(x=>setTimeout(x,5000));if(j.status!=='succeeded')throw Error(j.error||'Falló la generación');const d=await upload(path.join(VIDEOS,j.result.name),j.result);r.json({ok:true,title:j.result.title,video:d,project:j.result.projectUrl})}catch(e){r.status(500).json({error:e.message})}});
app.listen(PORT,'0.0.0.0',()=>console.log('AutoTube Studio activo en '+PORT));