const fs=require("fs"),fsp=fs.promises,path=require("path"),crypto=require("crypto");
module.exports=function(app){
 const root=path.resolve(process.cwd()), tokenFile=process.env.YOUTUBE_TOKEN_FILE||path.join(root,"data/youtube-token.json"), videoDir=path.join(root,"data/videos");
 fs.mkdirSync(path.dirname(tokenFile),{recursive:true});fs.mkdirSync(videoDir,{recursive:true});
 const cfg=()=>({id:process.env.YOUTUBE_CLIENT_ID,secret:process.env.YOUTUBE_CLIENT_SECRET,redirect:process.env.YOUTUBE_REDIRECT_URI});
 const signState=s=>crypto.createHmac("sha256",String(process.env.YOUTUBE_CLIENT_SECRET||"").trim()).update(s).digest("hex");
 const makeState=()=>{const s=crypto.randomBytes(20).toString("hex");return s+"."+signState(s)};
 const validState=s=>{const [raw,sig]=String(s||"").split(".");if(!raw||!sig)return false;const a=Buffer.from(sig),b=Buffer.from(signState(raw));return a.length===b.length&&crypto.timingSafeEqual(a,b)};
 const remoteReady=()=>!!(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY&&process.env.YOUTUBE_TOKEN_ENCRYPTION_KEY);
 const localToken=()=>{try{return JSON.parse(fs.readFileSync(tokenFile,"utf8"))}catch{return null}};
 const saveLocal=t=>fs.writeFileSync(tokenFile,JSON.stringify(t,null,2),{mode:0o600});
 const key=()=>crypto.createHash("sha256").update(process.env.YOUTUBE_TOKEN_ENCRYPTION_KEY||"").digest();
 const encrypt=t=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",key(),iv),data=Buffer.concat([c.update(JSON.stringify(t),"utf8"),c.final()]);return [iv.toString("base64"),c.getAuthTag().toString("base64"),data.toString("base64")].join(".")};
 const decrypt=s=>{const [iv,tag,data]=String(s).split("."),d=crypto.createDecipheriv("aes-256-gcm",key(),Buffer.from(iv,"base64"));d.setAuthTag(Buffer.from(tag,"base64"));return JSON.parse(Buffer.concat([d.update(Buffer.from(data,"base64")),d.final()]).toString("utf8"))};
 const supa=()=>String(process.env.SUPABASE_URL||"").trim().replace(/\/$/,"")+"/rest/v1/youtube_tokens";
 const token=async()=>{if(!remoteReady())return localToken();const r=await fetch(supa()+"?id=eq.default&select=payload",{headers:{apikey:String(process.env.SUPABASE_SERVICE_ROLE_KEY||"").trim(),Authorization:"Bearer "+String(process.env.SUPABASE_SERVICE_ROLE_KEY||"").trim()}});if(!r.ok)throw Error("No se pudo leer el almacenamiento seguro");const d=await r.json();return d[0]?.payload?decrypt(d[0].payload):null};
 const save=async t=>{if(!remoteReady())return saveLocal(t);const r=await fetch(supa(),{method:"POST",headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:"Bearer "+process.env.SUPABASE_SERVICE_ROLE_KEY,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({id:"default",payload:encrypt(t)})});if(!r.ok)throw Error("No se pudo guardar el token seguro")};
 const deleteToken=async()=>{if(!remoteReady()){try{if(fs.existsSync(tokenFile))fs.unlinkSync(tokenFile)}catch{}return}const r=await fetch(supa()+"?id=eq.default",{method:"DELETE",headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:"Bearer "+process.env.SUPABASE_SERVICE_ROLE_KEY}});if(!r.ok)throw Error("No se pudo eliminar la conexión")};
 const ready=()=>{const c=cfg();return !!(c.id&&c.secret&&c.redirect)};
 async function access(){
  let t=await token();if(!t)return null;
  if(t.access_token&&Date.now()-t.created_at<((t.expires_in||3600)-120)*1000)return t.access_token;
  if(!t.refresh_token)return t.access_token;
  const c=cfg(),r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.id,client_secret:c.secret,refresh_token:t.refresh_token,grant_type:"refresh_token"})}),d=await r.json();
  if(!r.ok)throw Error(d.error_description||d.error||"No se pudo renovar YouTube");
  await save({...t,...d,refresh_token:t.refresh_token,created_at:Date.now()});return d.access_token;
 }
 async function channel(){const a=await access();if(!a)return null;const r=await fetch("https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true",{headers:{Authorization:"Bearer "+a}}),d=await r.json();if(!r.ok)throw Error(d.error?.message||"YouTube rechazó la conexión");const x=d.items?.[0];return x&&{id:x.id,title:x.snippet?.title,thumbnail:x.snippet?.thumbnails?.default?.url};}
 app.get("/api/youtube/status",async(req,res)=>{try{if(!ready())return res.json({configured:false,connected:false});const c=await channel();res.json({configured:true,connected:!!c,channel:c,storage:remoteReady()?"supabase":"local"});}catch(e){res.json({configured:true,connected:false,error:e.message})}});
 app.get("/api/youtube/connect",(req,res)=>{if(!ready())return res.status(500).send("Configura YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET y YOUTUBE_REDIRECT_URI en Render.");const c=cfg(),state=crypto.randomBytes(20).toString("hex"),u=new URL("https://accounts.google.com/o/oauth2/v2/auth");u.searchParams.set("client_id",c.id);u.searchParams.set("redirect_uri",c.redirect);u.searchParams.set("response_type","code");u.searchParams.set("scope","https://www.googleapis.com/auth/youtube.upload");u.searchParams.set("access_type","offline");u.searchParams.set("prompt","consent");u.searchParams.set("state",state);res.redirect(u.toString())});
 app.get("/api/youtube/callback",async(req,res)=>{try{const state=String(req.query.state||"");if(!validState(state))throw Error("Estado OAuth no válido o caducado");const c=cfg(),r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code:String(req.query.code||""),client_id:c.id,client_secret:c.secret,redirect_uri:c.redirect,grant_type:"authorization_code"})}),d=await r.json();if(!r.ok)throw Error(d.error_description||d.error||"Autorización rechazada");await save({...d,created_at:Date.now()});res.redirect("/?youtube=connected")}catch(e){res.status(500).send("No se pudo conectar YouTube: "+e.message)}});
 app.post("/api/youtube/disconnect",async(req,res)=>{try{await deleteToken();res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
 async function upload(file){
  const a=await access();if(!a)throw Error("Primero vincula YouTube");const st=await fsp.stat(file),date=new Date().toLocaleDateString("es-ES",{timeZone:process.env.DAILY_TIMEZONE||"Europe/Madrid"}),init=await fetch("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status",{method:"POST",headers:{Authorization:"Bearer "+a,"Content-Type":"application/json","X-Upload-Content-Length":String(st.size),"X-Upload-Content-Type":"video/mp4"},body:JSON.stringify({snippet:{title:"RelaxScape · Naturaleza y relajación · "+date,description:"Vídeo original de relajación, naturaleza y sonidos ambientales creado con RelaxScape Studio.",tags:["relajación","naturaleza","meditación","sleep","relax","ambient"],categoryId:"22"},status:{privacyStatus:"public",selfDeclaredMadeForKids:false}})});
  const loc=init.headers.get("location");if(!init.ok||!loc){const d=await init.json().catch(()=>({}));throw Error(d.error?.message||"No se pudo iniciar la subida")};
  const r=await fetch(loc,{method:"PUT",headers:{Authorization:"Bearer "+a,"Content-Type":"video/mp4","Content-Length":String(st.size)},body:fs.createReadStream(file),duplex:"half"}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error?.message||"Falló la subida");return {id:d.id,url:"https://www.youtube.com/watch?v="+d.id};
 }
 app.post("/api/youtube/daily-publish",async(req,res)=>{try{if(process.env.YOUTUBE_PUBLISH_SECRET&&req.get("x-youtube-secret")!==process.env.YOUTUBE_PUBLISH_SECRET)throw Error("No autorizado");if(!await token())throw Error("Primero vincula YouTube");const port=Number(process.env.PORT||10000),s=await fetch("http://127.0.0.1:"+port+"/api/daily-video-now",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({durationMinutes:Number(req.body?.durationMinutes||60)})}),j=await s.json();if(!j.jobId)throw Error(j.error||"No se pudo iniciar el vídeo");let q;for(let i=0;i<900;i++){await new Promise(r=>setTimeout(r,2000));q=await (await fetch("http://127.0.0.1:"+port+"/api/daily-video-status?jobId="+j.jobId)).json();if(q.status==="succeeded")break;if(q.status==="failed")throw Error(q.error||"Falló la generación")}if(q?.status!=="succeeded")throw Error("La generación tardó demasiado");const file=path.join(videoDir,q.result.name);res.json({ok:true,result:await upload(file)});}catch(e){res.status(500).json({ok:false,error:e.message})}});
};